language: dart

dart:
  - 2.0.0
  - dev

dart_task:
  - test: -p vm
    xvfb: false
  - test: -p firefox
  - dartanalyzer: --fatal-infos --fatal-warnings .

matrix:
  include:
  # Only validate formatting using the dev release
  - dart: dev
    dart_task: dartfmt

cache:
  directories:
    - $HOME/.pub-cache
