name: matcher
version: 0.12.7

description: >-
  Support for specifying test expectations via an extensible Matcher class.
  Also includes a number of built-in Matcher implementations for common cases.
homepage: https://github.com/dart-lang/matcher

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  stack_trace: ^1.2.0

dev_dependencies:
  pedantic: ^1.4.0
  test: '>=0.12.0 <2.0.0'

dependency_overrides:
  test: ^1.12.0
  test_api: ^0.2.14
  test_core: ^0.3.0
